language: java
jdk:
- openjdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: LdV/a7o0q7qGwVXcMWe84dWkaoVhDkPo6G7b+WGyY9LGg0C4KcflOdO1OyrV/QX9D9tHbmg0S4NWzGMo/aTxiUbvRt8NhvCJqICmE9NPAZ5xMTfqD+LDqbsZlIyfSas+mS2t19p1p3k+9oLCw51+BNGX/rh1+rygPlDlNh3rsZRo7foH31jr855g7xLex4ldi5+DWN+JQ/gcrHVByCpKRt6TBtX1dBEbvW+GGsH597z+OncipusdgcVxchlwjDsj+upkEwtOg/sab2in0XlGD094Tl/eijfzSPgh0Q+VldCsAoVlXVCqm+iEGEfXs2Mi8bnQS4EDtLtWv19YZIPBSyP33Dk/Uqi7Slv9Q9/mT81544v9qTxgjIvfjudvIrUPuYTlhaYj4+stuk4PgA+h/Ov5AkQHzQ/rNhYE56UEN4hqHf0sqRQqnDU8u4Y8pxpTQBC64/WcW9jhj0fADQm798vKYjJEFLFqfA4iLq47Pkb7E5wYcB1NGAEPHvquCmrEqBIdpAzj2WtoOBf0rCPDTG+7GI+Rj9hVZskC5AyULi+S1cNyBosBDqoV7fMNvlFh9CBZN3Sp8Hc3QsrSoqnb7bh3urFlgzX5UqdZ+ynq1sx8I39WaYkHwwmY7cF5ixhrkI2WXl1B1lkGdRYJs+cmb/RUyc83VKSVKap1Rrurwqg=
  - secure: PTgQeI7P8soKnO3QBugAPpcIKTS2cgl8G7AUKrqABV8Y/VK/isVdXg+FvBmTtstxd4a0FVLbuEQPcaT8zp06uV03vCJKDTi8MR1fe4AFXIJGHDLQk7SnatgwjLRLr55z9ZGsFlbSvIN17gmPrJuw8bD3wXHAfy6OrRGikthvowtXU+k9MZ7OTNjMKAxHZmpPUbc3QkWE1+7yb38e2EaaisM6GhsiD/jFoU3CIIo8DytIPA66KxPpemSfjt56GZM2HoF9PB8ihSJXtYQ9n4D9xRBD7PYK3EVYEiw1/SPItASm+4at+qSjo4Ib4rahJADouBwi/K9P2aqw/8Dk9IdXhNil7g3uXpnK0rh9TkMWYfW/DRiAwkETk9/bpa52CNO54gWYVYZXPcQKMgIP1KW1v5nAvMQXwbvVxJqYLPDseT0a1W+TYvBY3su9wSmAFVdoWbE9PQuMoHzBBSTESNpL3GGcyd0vJ4DXSmeQgy2RvK4qggT9Riy5cVvG5kAcZH0Ea6agJLQ2hLrr4msMWJOQ4dDlGUxQ5R6ZLVTeexafP2Bbrhrtl7tL0XtumBMcHEGVl+URCmJOR4xNhvUQ/DrX4WhrMHf3cZpSx8dHW5xyIfsDBBszHGzhOoqf3FDysM2WkiGPRBQBKYt7wSiprg2gnV5X70Xe6hk/mCkEbaCxh6U=
